# Generated by Django 3.2.4 on 2021-06-07 12:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Place',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Address', models.CharField(blank=True, max_length=100)),
                ('BusinessName', models.CharField(blank=True, max_length=100)),
                ('Person', models.CharField(blank=True, max_length=100)),
                ('Contact', models.CharField(blank=True, max_length=100)),
                ('VerifiedStatus', models.BooleanField(default=True)),
                ('TimeStamp', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
